### ISSUE TITLE
Add info button to display rules of each game

### ISSUE THREAD

**Issue by magnetenstad** [ntnui-darts/darts.quest#64]

**Comment by Pooja1672** [comment]
Hi @magnetenstad , I would like to work on this issue can you please assign this to me?

**Comment by magnetenstad** [comment]
@Pooja1672 Thank you for wanting to contribute! 😊 I have now assigned this issue to you. Would you like a more detailed description of the task? Are you familiar with the game of darts and our webapp https://darts.quest ?
